# Generated by Django 4.2.1 on 2024-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagrapherapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("show_on_home", models.BooleanField(default=False)),
            ],
        ),
    ]
