# Generated by Django 4.2.1 on 2024-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datagrapherapp", "0003_stock_stockdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="url",
            field=models.CharField(default="home", max_length=255),
        ),
    ]
